services:
  postgres:
    image: postgres:16-alpine
    container_name: quickdelivery-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: quickdelivery
      POSTGRES_PASSWORD: quickdelivery
      POSTGRES_DB: quickdelivery
    ports:
      - "5432:5432"
    volumes:
      - quickdelivery-pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: quickdelivery-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: quickdelivery
      RABBITMQ_DEFAULT_PASS: quickdelivery
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - quickdelivery-rabbitmq-data:/var/lib/rabbitmq

volumes:
  quickdelivery-pgdata:
  quickdelivery-rabbitmq-data:
